PollRequest
perfomance-review/pr-frontend pull request #12
Opened 2022-05-28 18:24 UTC by NickKovtunov

2022-05-29 15:05 UTC, sabkaryan requested changes

2022-05-29 15:05 UTC, sabkaryan commented on src/API/PollService.js
> +    debugger
это можно удалить

2022-05-29 15:05 UTC, sabkaryan commented on src/API/PollService.js
> +      return response.data;
давай не будем модифицировать response, а вернём новый объект в том формате, который нам нужен

2022-05-29 15:05 UTC, sabkaryan commented on src/pages/Poll.jsx
> +  const [isPollsLoading, setIsPollsLoading] = useState(false);
```suggestion
  const [isPollLoading, setIsPollLoading] = useState(false);
```

2022-05-29 15:05 UTC, sabkaryan commented on src/pages/Poll.jsx
> +      })
этот catch избыточный мы в него никогда не попадём, потому что PollService уже ловит все исключения и никогда их дальше не прокидывает

2022-05-29 15:05 UTC, sabkaryan commented on src/pages/Poll.jsx
> +      .then(function (response) {})
давай уже тогда везде async/await синтаксис использовать чтобы везде единообразно было

2022-05-29 15:05 UTC, sabkaryan commented on src/pages/Poll.jsx
> +    PollService.startPoll(pollId,selectedUsers)
Давай попросим бэк положить в ответ на этот запрос опрос с новым статусом. А в коде этого компонента будем смотреть на статус опроса, если он начат то показывать компонент с оценкой
Это можно в другой задаче сделать

2022-05-30 14:24 UTC, NickKovtunov commented on src/API/PollService.js
> +    debugger
Удалил

2022-05-30 14:24 UTC, NickKovtunov commented on src/API/PollService.js
> +      return response.data;
Переделал. А почему не стоит модифицировать response? Ведь по факту почти ничего не изменилось

2022-05-30 14:24 UTC, NickKovtunov commented on src/pages/Poll.jsx
> +  const [isPollsLoading, setIsPollsLoading] = useState(false);
Исправил

2022-05-30 14:25 UTC, NickKovtunov commented on src/pages/Poll.jsx
> +      })
Убрал

2022-05-30 14:25 UTC, NickKovtunov commented on src/pages/Poll.jsx
> +      .then(function (response) {})
Согласен

2022-05-30 14:25 UTC, NickKovtunov commented on src/pages/Poll.jsx
> +    PollService.startPoll(pollId,selectedUsers)
Хорошо

2022-05-30 15:24 UTC, sabkaryan commented on src/API/PollService.js
> +      return response.data;
В твоём новом варианте ничего не изменилось. Я предлагаю новый объект собирать
```js
const myNewObject = {
    respondentsCount: response.data.respondents.length,
    respondents: response.data.respondents.map(item => ({id: item.userId, name: item.secondName + " " + item.firstName}))
}
```

2022-05-30 15:39 UTC, sabkaryan commented on src/pages/Poll.jsx
> +            options={poll.users.map(({ id, name }) => ({ label: name, value: id }))}
давай это в useMemo вынесем, чтобы каждый раз не пересчитывать

2022-05-30 16:21 UTC, NickKovtunov commented on src/API/PollService.js
> +      return response.data;
Понял, исправил

2022-05-30 16:21 UTC, NickKovtunov commented on src/pages/Poll.jsx
> +            options={poll.users.map(({ id, name }) => ({ label: name, value: id }))}
Вроде вынес правильно

2022-05-30 18:37 UTC, sabkaryan approved these changes

2022-05-31 02:50 UTC, merged